# Generated by Django 3.0.7 on 2020-08-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200731_2322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='blog_city',
        ),
    ]
