# Generated by Django 3.0.7 on 2020-08-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200806_2335'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='blog_country',
        ),
    ]
