# Generated by Django 3.0.7 on 2020-08-07 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200806_2336'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table='blog_state',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State')),
            ],
        ),
    ]
