# Generated by Django 3.0.7 on 2020-08-07 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200806_2340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='blog_city',
        ),
    ]
