# Generated by Django 3.0.7 on 2020-08-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200806_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phonecode',
        ),
        migrations.RemoveField(
            model_name='country',
            name='sortname',
        ),
    ]
