# Generated by Django 3.0.7 on 2010-02-25 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20100224_2349'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='state',
            table='blog_state',
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.State')),
            ],
        ),
    ]
